//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarioPizzaImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coupon()
        {
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public Nullable<int> applyon { get; set; }
        public string description { get; set; }
        public Nullable<int> productcategoryid { get; set; }
        public Nullable<int> isfordeliverytypeonly { get; set; }
        public Nullable<decimal> pricetreshold { get; set; }
    
        public virtual deliverytype deliverytype { get; set; }
        public virtual productcategory productcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
