
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MarioPizzaImport
{

using System;
    using System.Collections.Generic;
    
public partial class import_log
{

    public int id { get; set; }

    public Nullable<System.DateTime> time { get; set; }

    public string filename { get; set; }

    public string error { get; set; }

    public string type { get; set; }

}

}
