

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MarioPizzaImport
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class dbi298845_prangersEntities : DbContext
{
    public dbi298845_prangersEntities()
        : base("name=dbi298845_prangersEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<address> addresses { get; set; }

    public virtual DbSet<bottom> bottoms { get; set; }

    public virtual DbSet<bottomprice> bottomprices { get; set; }

    public virtual DbSet<countrycode> countrycodes { get; set; }

    public virtual DbSet<coupon> coupons { get; set; }

    public virtual DbSet<deliverytype> deliverytypes { get; set; }

    public virtual DbSet<ingredient> ingredients { get; set; }

    public virtual DbSet<ingredientprice> ingredientprices { get; set; }

    public virtual DbSet<order> orders { get; set; }

    public virtual DbSet<orderline> orderlines { get; set; }

    public virtual DbSet<postalcode> postalcodes { get; set; }

    public virtual DbSet<product> products { get; set; }

    public virtual DbSet<productcategory> productcategories { get; set; }

    public virtual DbSet<productingredient> productingredients { get; set; }

    public virtual DbSet<productorderingredient> productorderingredients { get; set; }

    public virtual DbSet<productordersauce> productordersauces { get; set; }

    public virtual DbSet<productprice> productprices { get; set; }

    public virtual DbSet<sauce> sauces { get; set; }

    public virtual DbSet<store> stores { get; set; }

    public virtual DbSet<township> townships { get; set; }

    public virtual DbSet<user> users { get; set; }

    public virtual DbSet<mapping> mappings { get; set; }

    public virtual DbSet<postalcode_import> postalcode_import { get; set; }

}

}

