//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarioPizzaImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.orderlines = new HashSet<orderline>();
        }
    
        public int id { get; set; }
        public System.DateTime datecreated { get; set; }
        public Nullable<System.DateTime> datedelivered { get; set; }
        public string phonenumber { get; set; }
        public string clientname { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> couponid { get; set; }
        public string remark { get; set; }
        public int deliverytypeid { get; set; }
        public int addressid { get; set; }
        public int storeid { get; set; }
        public System.DateTime preferredtime { get; set; }
        public decimal price { get; set; }
        public decimal discount { get; set; }
    
        public virtual address address { get; set; }
        public virtual coupon coupon { get; set; }
        public virtual deliverytype deliverytype { get; set; }
        public virtual user user { get; set; }
        public virtual store store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderline> orderlines { get; set; }
    }
}
