//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarioPizzaImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class postalcode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public postalcode()
        {
            this.addresses = new HashSet<address>();
        }
    
        public int id { get; set; }
        public string postalcode1 { get; set; }
        public bool iseven { get; set; }
        public int startingnumber { get; set; }
        public int endingnumber { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public int townshipid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<address> addresses { get; set; }
        public virtual township township { get; set; }
    }
}
