
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MarioPizzaImport
{

using System;
    using System.Collections.Generic;
    
public partial class postalcode_import
{

    public string postalcode { get; set; }

    public decimal iseven { get; set; }

    public decimal startingnumber { get; set; }

    public decimal endingnumber { get; set; }

    public string city { get; set; }

    public string street { get; set; }

    public string township { get; set; }

}

}
